#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

dunst &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf & 
xrandr --output HDMI-0 --primary &
nm-applet &
flameshot &
clipcatd &
sudo fancurve & 

nvidia-smi -q | rg -i "fan speed" | awk -F ':' '{print $2}' | sed 's/[^0-9]//ig' > $HOME/.gpu_fanspeed


#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Screen 1
monitor="HDMI-0" polybar -c $SCRIPTPATH/polybar.config first_screen_first_bar &> /dev/null &

# screen 2
monitor="DP-4" polybar -c $SCRIPTPATH/polybar.config second_screen_first_bar &> /dev/null &
monitor="DP-4" polybar -c $SCRIPTPATH/polybar.config second_screen_second_bar &> /dev/null &

